{% set name = "mmhash3" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mmhash3-{{ version }}.tar.gz
  sha256: a00d68f4a1cc434b9501513c8a29e18ed1ddad383677d72b41d71d0d862348af

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: True  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - mmh3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Fokko/mmhash3
  dev_url: https://github.com/Fokko/mmhash3
  doc_url: https://github.com/Fokko/mmhash3/blob/master/README.md
  summary: Python wrapper for MurmurHash (MurmurHash3), a set of fast and robust hash functions.
  description: |
    mmhash3 is a Python wrapper for MurmurHash (MurmurHash3), a set of fast 
    and robust non-cryptographic hash functions invented by Austin Appleby.
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
